# Generated by Django 6.0.6 on 2026-06-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_alter_task_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='type_old',
        ),
    ]
