# Generated by Django 6.0.6 on 2026-06-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_rename_type_task_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='tasks', to='issue_tracker.type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks_old', to='issue_tracker.type'),
        ),
    ]
