# Generated by Django 6.0.6 on 2026-06-11 12:31

from django.db import migrations

def transfer_types(apps, schema_editor):
    Task = apps.get_model('issue_tracker', 'Task')
    for task in Task.objects.all():
        task.type.set([task.type_old])

def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('issue_tracker', 'Task')
    for task in Task.objects.all():
        first_type = task.type.first()
        if first_type:
            task.type_old = first_type
            task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_task_type_alter_task_type_old'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer),
    ]
