# Generated by Django 6.0.6 on 2026-06-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_auto_20260611_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_old',
        ),
    ]
