# Generated by Django 6.0.5 on 2026-06-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0011_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('manage_project_users', 'Can manage project users')]},
        ),
    ]
